Move Monolog to dev
browscap/browscap-php pull request #660
Opened 2024-01-08 15:21 UTC by mostafasoufi

Regarding PR #465, why isn't MonoLog included in the development environment when it's used in the Commands classes for Unit tests?

Best

2024-01-08 17:52 UTC, mimmi20 commented
@mostafasoufi Monolog is used in the File `src/Helper/LoggerHelper.php`. This Helper is used in all Commands, not just in the Tests. If you want to make Monolog optional, you have to change that file too, and maybe all places where this Helper is used.

2024-01-08 18:02 UTC, mostafasoufi commented
They are only uses in `/bin/browscap-php` which is not the main functionality of Browscap, isn't it?

2024-01-08 19:03 UTC, mimmi20 commented
Browscap can be used in two ways:

1. as Component for other projects, where it is installed via composer
2. as Standalone Project

In the second Way, you can use these Commands. I do not know, if anyone uses Browscap this way.

If `Monolog` is transfered to the dev-section, these Commands will break. This means that will be a breaking change.

2024-01-08 19:07 UTC, mimmi20 requested changes
Please add also an Comment in the Readme (where these Commands are listed), that the User has to install Monolog.

2024-01-08 19:07 UTC, mimmi20 commented on composer.json
> +        "monolog/monolog": "^3.5.0",
Please add `"monolog/monolog"` also in the `suggest` section with an comment, that this is required for the console commands.

2024-01-08 19:16 UTC, asgrim commented
I would suggest this is not mergable at least until the next major, since it would indeed break this functionality. It would help if we knew if people use this functionality or not 🤷

2024-01-08 20:24 UTC, asgrim commented
@mostafasoufi thank you for the PR, but since this is functionality people may use, which would break, this wouldn't be acceptable until a major release really. I'd suggest making an issue to see if others have feedback about it and we can discuss what the migration path might look like. Thank you though, we really appreciate it!

2024-01-08 20:24 UTC, closed without merging

2024-01-09 07:19 UTC, mostafasoufi commented
I inquired because I'm planning to upgrade Browscap for WordPress plugins like **[WP Statistics](https://wordpress.org/plugins/wp-statistics)** and **[SlimStat Analytics](https://wordpress.org/plugins/wp-slimstat/)**. However, since the pull request (PR) is closed, it looks like I'll need to fork the project and work on my own repository.